legacy_layout=0
fps=0
cpu_stats=0
gpu_stats=0

# Style setup
font_file=/home/jblyberg/.local/share/fonts/ComicCodeLigaturesNerdFont-Bold.otf
font_size=72
font_scale=1.0
text_outline=0
background_alpha=0.0
position=top-left
width=200
height=100
horizontal
offset_x=-28
text_color=71697A

exec=/home/jblyberg/.config/MangoHud/hud-text.sh
