monitor.alsa.rules = [
  {
    matches = [
      {
        # Matches ALL ALSA audio output nodes (USB, PCI, HDMI)
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        # Drop audio.format so it dynamically matches the individual 
        # formats of your Corsair headset vs your PCI card safely.
        api.alsa.disable-tsched = true
        api.alsa.period-size    = 1024
        api.alsa.headroom       = 512
      }
    }
  }
]
