monitor.alsa.rules = [
  {
    matches = [
      {
        # Disable Navi 31 device
        device.name = "alsa_card.pci-0000_0d_00.1" 
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
