cursor #e0e2e8
cursor_text_color #c2c7cf

foreground            #e0e2e8
background            #101418
selection_foreground  #243240
selection_background  #b9c8da
url_color             #9dcbfb

color0   #101418
color1   #ff729c
color2   #7dfb8e
color3   #fff772
color4   #83b7ee
color5   #244b74
color6   #9dcbfb
color7   #eff7ff
color8   #969ca3
color9   #ff9fbb
color10  #a5ffb1
color11  #fffaa5
color12  #add5ff
color13  #bcdcff
color14  #d4e9ff
color15  #f8fbff
