# Fonts

font_family      ComicCodeLigatures Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15

# text_composition_strategy legacy 
# modify_font cell_width 100%

# Keyboard map

map cmd+shift+l next_layout
map cmd+shift+t goto_layout tall
map cmd+shift+s goto_layout stack

# Cursor

shell_integration no-cursor
cursor #bcc1dd
cursor_text_color #161824
cursor_shape block
cursor_blink_interval 0

# Windows

window_padding_width 0 3

# Layouts - hit ctrl-shift-enter to add windows

enabled_layouts tall:bias=62;full_size=1;mirrored=true

# Colors

foreground #bcc1dd
background #161824

selection_foreground #c9d1fb
selection_background #333852

active_border_color #5d5d5d
inactive_border_color #2d2d2d

## Black
color3 #717171
color11 #717171

## Red
color1  #e67d8f
color9 #e67d8f

## Green
color2  #63b29c
color10 #63b29c

## Magenta
color6  #d8b072
color14 #d8b072

## Blue
color4  #83a0ec
color12 #83a0ec

## Yellow
color5  #b59bf0
color13 #b59bf0

## Cyan
color7  #60c1db
color15 #60c1db


