[mgr]

prepend_keymap = [
  # { on = "<Enter>", run = "enter" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "<C-w>", run = 'shell -- dms ipc call wallpaper set "$0"', desc = "Set hovered file as wallpaper", for = "linux" },
  { on = "<S-down>", run = "arrow 15" },
  { on = "<S-up>", run = "arrow -15" },
  { on = "<S-y>", run = "plugin wl-copy", for = "linux" },
  { on = "<S-y>", run = "plugin clippy-copy", for = "macos" },
  { on = "<S-p>", run = "plugin save-clipboard-to-file", desc = "Paste clipboard content to file and hover after created", for = "linux" },
  { on = "<S-p>", run = "plugin clippy-paste", desc = "Paste clipboard content to file and hover after created", for = "macos" },
  { on = "k", run = "plugin parent-arrow -1" },
  { on = "j", run = "plugin parent-arrow 1" },
  { on = [
    "f",
    "r",
  ], run = "plugin fr rg", desc = "Search file by content (rg)" },
  { on = [
    "f",
    "a",
  ], run = "plugin fr rga", desc = "Search file by content (rga)" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to the root of current Git repository." },

]
