[mgr]

ratio = [1, 3, 4]
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"
sort_by = "alphabetical"
sort_reverse = false
show_hidden = false
show_symlink = true
scrolloff = 5

[preview]

cache_dir = "~/.local/cache/yazi"
max_height = 1500
max_width = 1500
wrap = "yes"

[opener]
audio = [{ run = 'decibels "$@"', desc = "Play Audio File", for = "linux" }]
image = [{ run = 'loupe "$@"', desc = "Open Image", for = "linux" }]
video = [{ run = 'showtime "$@"', desc = "Play Video File", for = "linux" }]

# open_exe = [{ run = 'wine "$@"', desc = "Open Windows Application" }]
exe = [
  { run = 'umu-run "$@" -opengl -SkipBuildPatchPrereq', desc = "Open Windows Application" },
]


pdf = [
  { run = 'evince "$@"', desc = "Open PDF", for = "linux" },
  { run = 'open "$@"', desc = "Open PDF", for = "macos" },
]

wallpaper = [
  { run = 'dms ipc call wallpaper set "$1"', desc = "Set as Wallpaper", for = "linux" },
]

[open]
prepend_rules = [
  { name = "*.exe", use = "exe" },
  { name = "*.pdf", use = "pdf" },
  { mime = "audio/*", use = "audio" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
]

[plugin]

prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },

  # { id = "mactag", url = "*", run = "mactag" },
  # { id = "mactag", url = "*/", run = "mactag" },
]

prepend_preloaders = [
  # Office Documents
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { name = "*.docx", run = "office" },

  # 3d objects
  { name = "*.3mf", run = "f3d-preview" },
  { name = "*.obj", run = "f3d-preview" },
  { name = "*.pts", run = "f3d-preview" },
  { name = "*.ply", run = "f3d-preview" },
  { name = "*.stl", run = "f3d-preview" },
  { name = "*.step", run = "f3d-preview" },
  { name = "*.stp", run = "f3d-preview" },
  { name = "*.skp", run = "f3d-preview" },

  { mime = "audio/*", run = "audio-preview" },
]

prepend_previewers = [
  # Office Documents
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "video/*", run = "video-ffmpeg" },
  { name = "*.docx", run = "office" },

  # 3d objects
  { name = "*.3mf", run = "f3d-preview" },
  { name = "*.obj", run = "f3d-preview" },
  { name = "*.pts", run = "f3d-preview" },
  { name = "*.ply", run = "f3d-preview" },
  { name = "*.stl", run = "f3d-preview" },
  { name = "*.step", run = "f3d-preview" },
  { name = "*.stp", run = "f3d-preview" },
  { name = "*.skp", run = "f3d-preview" },

  # Code
  { mime = "*/javascript", run = "code" },
  { mime = "*/typescript", run = "code" },
  { mime = "*/x-wine-extension-ini", run = "code" },
  { mime = "*/xml", run = "code" },
  { mime = "text/*", run = "code" },
  { name = "*.json", run = "code" },
  { name = "*.md", run = "code" },

  { mime = "audio/*", run = "audio-preview" },
  { mime = "application/bittorrent", run = "torrent-preview" },
]
